---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
  #- name: add MS Repo
#    yum_repository:
#      name: mslinux
#      description: microsoft for linux
#      baseurl: https://packages.microsoft.com/config/fedora/27/packages-microsoft-prod.rpm
#      enabled: 1
#      repo_gpgcheck: 0
#      gpgcheck: 1
#      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      
  - name: Add docker repo
    shell: dnf install python-dnf

  - name: Install Core Packages 
      dnf: 
        name: ['htop', 'iotop', 'chromium', 'https://go.microsoft.com/fwlink/?LinkID=760681', 'dnf-plugins-core']

  - name: Remove existing unofficial Docker packages
      dnf: 
        name: ['docker', 'docker-common', 'container-selinux', 'docker-selinux']
        state: absent

  - name: Add docker repo
      shell: 'dnf config-manager \
        --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo'

  - name: Install Docker 
      dnf:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

  - name: Start docker service
    systemd:
      state: started
      name: docker
    
#######################
# GNOME Scroll Bars.
#cd ~/.config/gtk-4.0/
# or maybe 3.0
# touch gtk.css
# vi gtk.css
#scrollbar {
#    min-width: 15px;
#    min-height: 15px;
#}
#########################
...