- hosts: localhost
  become: true
  tasks:
  - name: Install Packages 
    dnf: name={{item}}
    with_items:
    - htop
    - iotop
    - chromium
    - code
    - https://go.microsoft.com/fwlink/?LinkID=760681
    
