---
- hosts: localhost
  become: true
# become_method: sudo
  tasks:
  #- name: add MS Repo
#    yum_repository:
#      name: mslinux
#      description: microsoft for linux
#      baseurl: https://packages.microsoft.com/config/fedora/27/packages-microsoft-prod.rpm
#      enabled: 1
#      repo_gpgcheck: 0
#      gpgcheck: 1
#      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
#'https://go.microsoft.com/fwlink/?LinkID=760681',
      
  - name: Install Core Packages 
    dnf:
      name: ['python-dnf','htop', 'iotop', 'chromium', 'dnf-plugins-core']

  - name: Remove existing unofficial Docker packages
    dnf: 
      name: ['docker', 'docker-common', 'container-selinux', 'docker-selinux']
      state: absent
  
  - name: Remove unwanted sotware
    dnf: 
      name: ['libreoffice*', 'firefox', 'evolution' ,'contacts']
      state: absent
  
  - name: Add docker repo
    shell: 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'

  - name: Install Docker 
    dnf: 
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

  - name: Start docker service
    systemd:
      state: started
      name: docker

  - name: set microsoft repo
    yum_repository:
      name: code
      description: vscode
      file: vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      baseurl: https://packages.microsoft.com/yumrepos/vscode

  - name: install vscode
    dnf:
      name: code
      state: latest
    
#######################
# GNOME Scroll Bars.
#cd ~/.config/gtk-4.0/
# or maybe 3.0
# touch gtk.css
# vi gtk.css
#scrollbar {
#    min-width: 15px;
#    min-height: 15px;
#}
#########################
...